### ISSUE TITLE
Question & bug wrapper min-height 

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#1491]
Hi,

I need information on how the JS is calculating the minimum height.
When a page does not have a lot of content and having long menu with sub-menus
it is impossible to get the bottom menu items before closing the parent menu item

This is not a  blocking issue as if I close the parent menu then it's ok
but if we can adjust not having this situation this will be great
Thanks

**Comment by almasaeed2010** [comment]
Could you try upgrading to the latest `master` version. We are hoping that the changes there would fix many layout issues. Please review the upgrade guide here: https://adminlte.io/docs/2.4/upgrade-guide

Thanks!

**Comment by sdjeffal** [comment]
i have same problem, i download the last release v2.3.11. can you help please.
![capture d ecran 2017-06-30 a 18 05 06](https://user-images.githubusercontent.com/17531121/27744162-c2d7e962-5dbe-11e7-9236-e9a57da93e36.png)

**Comment by Th3M3** [comment]
@lenamtl 
If your issue occurs on small content and a very long menu, then updating to the latest version should fix it for you.

Are you have a app.min.js or adminlte.min.js in your template?

Your issue is really different to mine. 
I made an PR (#1569) which has been closed and it seems that the maintainer applied some fixes for it.
So for your case (if menu's height more then window's height) it should work now.
But for my case (if heights of menus **and** content are less then window's height) the footer still not aligns not to the page's bottom.

If you're understanding js, then you can have a look how it's get calculated:
https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/adminlte.js#L603
https://github.com/almasaeed2010/AdminLTE/blob/master/build/js/Layout.js#L86

**Comment by lenamtl** [comment]
Hi

@Th3M3 as the project is almost completed I'm still using 2.3.3 I have not updated to 2.4

I did a quick test and issue was still present at that time, so that was not worth the trouble to update
(in my case the project have a lot of custom code)
The problem is seem to be present on 2.4.2  as other users reported a similar problem.

The newest JS code you pointed is more understandable than the previous one for the calculation....

So for me the min-height quick fix was the best solution, not perfect as I mentioned in this question as I hope to find a fix for the menu in some rare cases..

I replaced body and wrapper CSS
`height: 100%;` 
to a minimum height 
`min-height: 100%;`

**Comment by lenamtl** [comment]
Hi, 
I know this is very old question but this may help someone, I add this for a reference only.
I changed the apps.js code using the following fix and this is working fine without the need to update the 2.4.18
Fix #1276
https://github.com/duleorlovic/AdminLTE/commit/955fe63b15674a1a096097865324aa2be11f20f5
