### ISSUE TITLE
Unable to expand sidebar in Dashboard2 in V3

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2132]
### Environment:
* AdminLTE Version:  V3 beta1
* Operating System:  Linux Debain base
* Browser (Version):  Chrome Latest

### Description:
Every things working fine but i found one tiny bug in dashboard 2 in V3 beta1. 
When ever I collapsed sidebar I can't able to toggle it again
https://adminlte.io/themes/dev/AdminLTE/index2.html
Another one bug is empty space after collapse sidebar as in fig below
![Screenshot from 2019-06-14 19-32-13](https://user-images.githubusercontent.com/28560875/59514142-f9b6ce80-8edb-11e9-8598-6b04a1bbca61.png)

**Comment by REJack** [comment]
I‘ll check that later, thanks for reporting that issue.

**Comment by REJack** [comment]
I've fixed this issue, you can check the demo again.

**Comment by saileshkush95** [comment]
Thanks for your work but  issue is still available in hamburger icon
![Screenshot_20190620_145324](https://user-images.githubusercontent.com/28560875/59837788-8eeb1480-936d-11e9-9249-f11e35d7ec39.png)

**Comment by REJack** [comment]
Oh damn, I'll look to fix it for Chrome too.
