### ISSUE TITLE
[BUG] Long links in left sidebar do not display correctly

### ISSUE THREAD

**Issue by Gouttfi** [ColorlibHQ/AdminLTE#3367]
**Describe the bug**
When I use long links name in the sidebar, they are not displayed correctly. The icons in right are hidden by the main content.

**To Reproduce**
1. Go to the demo website : https://adminlte.io/themes/v3/index2.html
2. Open the browser console and edit any navbar title : 
![image](https://user-images.githubusercontent.com/56838707/106391077-c942e180-63eb-11eb-9cf4-3f184803257a.png)
3. See error

**Expected behavior**
I expected the name do not exceed the sidebar, and the icons to not be shifted to the right. 

**Screenshots**

Default : 
![image](https://user-images.githubusercontent.com/56838707/106391026-90a30800-63eb-11eb-877e-96fd4f3eed24.png)

With long title : 
![image](https://user-images.githubusercontent.com/56838707/106391008-779a5700-63eb-11eb-883c-57ce7e6bdc58.png)
We can see the title who are cut, the "new", "6" and arrows labels disappeared.

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0-rc
- Operating System:  Windows 10
- Browser (Version): Firefox 85.0

Is there a class to modify somewhere that I haven't seen? 
Thank you !

**Comment by danny007in** [comment]
already fixed in https://github.com/ColorlibHQ/AdminLTE/pull/3151

**Comment by REJack** [comment]
Duplicate of #2416, checkout this https://github.com/ColorlibHQ/AdminLTE/issues/2416#issuecomment-558622865

**Comment by Gouttfi** [comment]
Thanks for your answer,
your solutions work for correcting the disappearing labels issue, but I still don't see all the text, because there is no line break.
Changing the sidebar text size is not enough.
