### ISSUE TITLE
[Question] How to set a default display page (could be same as from the sidebar trigger) in IFrame mode?

### ISSUE THREAD

**Issue by huskier** [ColorlibHQ/AdminLTE#3408]
Hi,

When we open the example "iframe.html" from the root directory of AdminLTE-3.1.0-rc, there is initially no opened tab page at all, only show a message "No tab selected!" in the IFrame area.

Could we set a default display page (could be same as the one from the sidebar trigger) in the IFrame mode?

Thanks.
Youbao

**Comment by danny007in** [comment]
we will add in version 3.1.1

**Comment by REJack** [comment]
> we will add in version 3.1.1

Nope, you need to understand versioning. A v3.1.1 would only bring hotfixes/patches not new features. The next feature adds will come with the v4 development.

**Comment by huskier** [comment]
@danny007in @REJack  Thank you for your consideration.

**Comment by REJack** [comment]
I've added a fix to create a start page in IFrame mode, you only need to create the nav-item and tab-pane by yourself otherwise it would create creepy hide/show events of the empty/loading screen.

Here is my HTML Markup for a start page, the tab-pane need to be before the .tab-empty to get the correct style.

```html
  <div class="content-wrapper iframe-mode" data-widget="iframe" data-loading-screen="750">
    <div class="nav navbar navbar-expand-lg navbar-white navbar-light border-bottom p-0">
      <a class="nav-link bg-danger" href="#" data-widget="iframe-close">Close</a>
      <a class="nav-link bg-light" href="#" data-widget="iframe-scrollleft"><i class="fas fa-angle-double-left"></i></a>
      <ul class="navbar-nav" role="tablist">
        <li class="nav-item active" role="presentation"><a class="nav-link active" data-toggle="row" id="tab-index" href="#panel-index" role="tab" aria-controls="panel-index" aria-selected="true">Dashboard v1</a></li>
      </ul>
      <a class="nav-link bg-light" href="#" data-widget="iframe-scrollright"><i class="fas fa-angle-double-right"></i></a>
      <a class="nav-link bg-light" href="#" data-widget="iframe-fullscreen"><i class="fas fa-expand"></i></a>
    </div>
    <div class="tab-content">
      <div class="tab-pane fade active show" id="panel-index" role="tabpanel" aria-labelledby="tab-index"><iframe src="./index.html" style="height: 671px;"></iframe></div>
      <div class="tab-empty">
        <h2 class="display-4">No tab selected!</h2>
      </div>
      <div class="tab-loading">
        <div>
          <h2 class="display-4">Tab is loading <i class="fa fa-sync fa-spin"></i></h2>
        </div>
      </div>
    </div>
  </div>
```

**Comment by REJack** [comment]
I added this markup in the docs 😄

**Comment by huskier** [comment]
Thank you very much. @REJack @danny007in

**Comment by huskier** [comment]
@REJack Hi Jack, after testing the default page function, I've found that：
1. There is no CLOSE(X) symbol on the tab of the default page;
2. Although I put a page as the default page from the left-sidebar, when I click(trigger) the same page from the left-sidebar, a new tab is opened instead of display the default page (the same as the just triggered left-sidebar page). However, when I highlight the default page through click the tab, the corresponding item is also highlighted.
EXPECTED BEHAVIOR：
1) If the default page is one of the left-sidebar page, when I click(trigger) the same page from the left-sidebar, the default page should be active, instead of opening a new tab page;
2) When I highlight the default page through click the tab, the corresponding item is highlighted (This is OK for the presentated implementation).

**Comment by danny007in** [comment]
does this solved in latest version 3.1

**Comment by huskier** [comment]
@danny007in Hi Daniel, these two issues are still there in the latest version 3.1.

**Comment by danny007in** [comment]
Give some more details regarding of issue like code, images, video to solve the issue

**Comment by danny007in** [comment]
@REJack  can add this in docs

**Comment by REJack** [comment]
I'll update later the docs with the reworked IFrame HTML Markup.

**Comment by REJack** [comment]
fixed with eb5be81

**Comment by huskier** [comment]
@REJack Hi Jack, thanks for your work! Now the CLOSE(X) symbol is on the tab of the default page.

The following issue is still there.
Although I put a page as the default page from the left-sidebar, when I click(trigger) the same page from the left-sidebar, a new tab is opened instead of display the default page (the same as the just triggered left-sidebar page). However, when I highlight the default page through click the tab, the corresponding item is also highlighted.

EXPECTED BEHAVIOR：
a) If the default page is one of the left-sidebar page, when I click(trigger) the same page from the left-sidebar, the default page should be active, instead of opening a new tab page; **[This issue is still there.]**
b) When I highlight the default page through click the tab, the corresponding item is highlighted (This is OK for the presentated implementation).**[This is as expected behavior.]**

**Comment by huskier** [comment]
One more issue:
After upgrading to the latest master, when we click the left-sidebar item, the corresponding html page is loaded in the Browser's same tab, instead of opening in the AdminLTE's right-part's new tab.

Because of the modern browsers' cache technique, this issue does not present when the browsers' cache is not clear.

This issue is occured in the latest Chrome, Edge, and Firefox.

**Comment by REJack** [comment]
I've fixed it :D f545979c6412f71002e7f1061817bfba3e995464 please test it later with the RC version, there are still some flick issues on site loading but sadly the JS wont let me fix it now, with v4 we will remove the JS for this and calculate anything via CSS to reduce this flickerings
